services:
  coredns:
    image: coredns/coredns:1.8.6
    container_name: cs30coredns01
    restart: always
    command: -conf /root/Corefile
    expose:
    - '53/udp'
    ports:
    - '53:53/udp'
    volumes:
     - '$PWD/config:/root'
