services:
  coredns:
    image: coredns/coredns:1.8.6
    container_name: coredns-server
    restart: always
    expose:
    - '53'
    - '53/udp'
    ports:
    - '5300:53'
    - '5300:53/udp'
    volumes:
     - './config:/root'
